name: lunr
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0 # For Windows/Linux/macOS
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1
  animations: ^2.0.8
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  qr_flutter: ^4.1.0
  image_picker: ^1.0.7
  http_parser: ^4.0.2
  image_cropper: ^8.0.2
  equatable: ^2.0.5
  permission_handler: ^11.0.1
  file_saver: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
